#!/bin/bash
set -euo pipefail

_project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/.."

require-command() {
	local _command="${1?"command is required"}"

	if ! command -v "$_command" >/dev/null 2>&1; then
		echo "$_command is required"
		exit 1
	fi
}

update-tools() {
	pushd "$_project_root"

	require-command asdf

	asdf install action-validator latest
	asdf set action-validator latest
	asdf install nodejs latest:20
	asdf set nodejs latest:20

	popd
}

run() {
	local _command="$1"
	case "$_command" in
	tools)
		update-tools
		;;
	*)
		echo "unknown command $_command"
		exit 1
		;;
	esac
}

run "${1?'command is required'}"
